name: Build Images

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build API image
        run: docker build -t finance-o-matic-api ./apps/api
      - name: Build Web image
        run: docker build -t finance-o-matic-web ./apps/web
